import type { RacerDefinition } from './Racer';

/**
 * 제1회 초현실 경마 그랑프리 출전 선수 명단.
 * 새 캐릭터 추가: 여기에 정의 + RacerFactory 에 placeholder 빌더 + RaceEngine 의 능력 분기.
 */
export const RACER_DEFINITIONS: RacerDefinition[] = [
  {
    id: 'costume',
    number: 1,
    name: '말탈 브라더스',
    nameEn: 'HORSE COSTUME BROS',
    nameJa: 'ウマかぶり兄弟',
    emoji: '🎭',
    speed: 16.9,
    acceleration: 3.6,
    stamina: 0.55,
    cornering: 0.3,
    weight: 140,
    luck: 0.3,
    specialAbility: 'COSTUME',
    abilityName: '직선 폭주 / 탈 벗겨짐',
    abilityDesc: '말탈을 뒤집어쓴 두 사람. 사람 다리로 뛰는데 직선에서는 의외로 빠르다. 코너에서 탈이 벗겨지며 무너질 수 있지만 다시 뒤집어쓰고 달린다.',
    description: '2인 1조. 앞사람이 머리, 뒷사람이 엉덩이 담당.',
    bodyColor: 0x7a4a2a,
    clothColor: 0xf2f2f2,
    silksColor: 0xd94b3a,
    noseOffset: 2.5,
    strideLength: 3.4,
  },
  {
    id: 'longbody',
    number: 2,
    name: '롱바디 익스프레스',
    nameEn: 'LONGBODY EXPRESS',
    nameJa: 'ロングボディ・エクスプレス',
    emoji: '🐎',
    speed: 16.2,
    acceleration: 4.2,
    stamina: 0.7,
    cornering: 0.35,
    weight: 780,
    luck: 0.5,
    specialAbility: 'LONGBODY',
    abilityName: '쭈우욱 스트레치',
    abilityDesc: '평소엔 조금 긴 2인승 경주마. 그런데 결승선 앞에서 갑자기 몸통이 쭈우욱 늘어나 머리부터 골인한다. 레이스 중간에도 예고 없이 늘어날 수 있다.',
    description: '앞기수와 뒷기수의 호흡이 관건.',
    bodyColor: 0x6b3f22,
    clothColor: 0x2b56c7,
    silksColor: 0x3ea0e6,
    noseOffset: 3.0,
    strideLength: 6.4,
  },
  {
    id: 'elephant',
    number: 3,
    name: '킹 엘리펀트',
    nameEn: 'KING ELEPHANT',
    nameJa: 'キング・エレファント',
    emoji: '🐘',
    speed: 15.4,
    acceleration: 1.9,
    stamina: 0.95,
    cornering: 0.6,
    weight: 4200,
    luck: 0.5,
    specialAbility: 'ELEPHANT',
    abilityName: '최후의 돌진',
    abilityDesc: '자신을 말이라고 굳게 믿는 코끼리. 느리지만 절대 밀리지 않고, 막판에 갑자기 돌진해 주변을 쓸어버린다.',
    description: '체중 4.2톤. 기수는 아직 이 사실을 모른다.',
    bodyColor: 0x8b8a90,
    clothColor: 0x3b2fa8,
    silksColor: 0xf5c400,
    noseOffset: 2.9,
    strideLength: 4.4,
  },
  {
    id: 'cow',
    number: 4,
    name: '레이지 불',
    nameEn: 'RAGE BULL',
    nameJa: 'レイジ・ブル',
    emoji: '🐄',
    speed: 15.7,
    acceleration: 2.6,
    stamina: 0.7,
    cornering: 0.5,
    weight: 820,
    luck: 0.4,
    specialAbility: 'COW',
    abilityName: '흥분 폭주',
    abilityDesc: '말 장비를 착용한 소. 초반엔 느긋하지만 흥분하면 머리를 흔들며 폭주해 앞 선수를 들이받는다.',
    description: '오늘 아침 여물을 먹지 못했다고 한다.',
    bodyColor: 0xf4f0e6,
    clothColor: 0x1d8a3c,
    silksColor: 0xffffff,
    noseOffset: 2.5,
    strideLength: 5.2,
  },
  {
    id: 'motorcycle',
    number: 5,
    name: '모터 스탤리온',
    nameEn: 'MOTOR STALLION',
    nameJa: 'モーター・スタリオン',
    emoji: '🏍️',
    speed: 15.4,
    acceleration: 2.4,
    stamina: 1.0,
    cornering: 0.5,
    weight: 320,
    luck: 0.45,
    specialAbility: 'MOTORCYCLE',
    abilityName: '엔진 부스터',
    abilityDesc: '리젠트 머리에 선글라스를 낀 검은 말. 등에 할리 핸들과 배기관을 달았고 기수는 초퍼처럼 젖혀 앉는다. 초반엔 얌전하지만 중후반 엔진(?) 부스터가 터지면 뒷발로 튀어나가며 잔상을 남긴다. 가끔 엔진이 고장난다.',
    description: '말인데 엔진 소리가 난다. 심사위원회는 묻지 않기로 했다.',
    bodyColor: 0x2a2a2e,
    clothColor: 0xff6a00,
    silksColor: 0x101010,
    noseOffset: 2.1,
    strideLength: 8.0,
  },
  {
    id: 'human',
    number: 6,
    name: '휴먼 러너',
    nameEn: 'HUMAN RUNNER',
    nameJa: 'ヒューマン・ランナー',
    emoji: '🏃',
    speed: 16.5,
    acceleration: 5.2,
    stamina: 0.42,
    cornering: 0.65,
    weight: 85,
    luck: 0.5,
    specialAbility: 'HUMAN',
    abilityName: '두 발 전력질주',
    abilityDesc: '네 발로 뛰며 기수를 태운 사람. 스태미나가 매우 낮아 금방 지치지만, 가끔 일어나서 두 발로 전력질주한다.',
    description: '본인은 말이라고 주장한다. 기수는 무겁다.',
    bodyColor: 0xe8b894,
    clothColor: 0xb02a8f,
    silksColor: 0xffe14d,
    noseOffset: 1.15,
    strideLength: 2.3,
  },
  {
    id: 'giraffe',
    number: 7,
    name: '롱넥 미라클',
    nameEn: 'LONGNECK MIRACLE',
    nameJa: 'ロングネック・ミラクル',
    emoji: '🦒',
    speed: 16.3,
    acceleration: 3.0,
    stamina: 0.75,
    cornering: 0.45,
    weight: 1200,
    luck: 0.55,
    specialAbility: 'GIRAFFE',
    abilityName: '사진 판정의 목',
    abilityDesc: '목이 화면 밖으로 나가는 기린. 결승선에서 목을 앞으로 뻗어 사진 판정에서 유리하다. 가끔 옆 선수를 목으로 친다.',
    description: '높이 5.4m. 기수는 고소공포증이 있다.',
    bodyColor: 0xe0a743,
    clothColor: 0xd12d2d,
    silksColor: 0x2fb75e,
    noseOffset: 1.1,
    strideLength: 6.0,
  },
  {
    id: 'classic',
    number: 8,
    name: '클래식 호스',
    nameEn: 'CLASSIC HORSE',
    nameJa: 'クラシック・ホース',
    emoji: '🐴',
    speed: 15.7,
    acceleration: 4.0,
    stamina: 0.8,
    cornering: 0.85,
    weight: 500,
    luck: 0.12,
    specialAbility: 'CLASSIC',
    abilityName: '정상적인 말',
    abilityDesc: '유일하게 평범한 경주마. 능력치는 우수하지만 다른 선수들의 사고에 계속 휘말리는 불운을 타고났다.',
    description: '오늘만큼은 평범하게 달리고 싶다.',
    bodyColor: 0x4a2c17,
    clothColor: 0x111111,
    silksColor: 0x8a2be2,
    noseOffset: 2.4,
    strideLength: 6.6,
  },
  {
    id: 'circus',
    number: 9,
    name: '서커스 스타',
    nameEn: 'CIRCUS STAR',
    nameJa: 'サーカス・スター',
    emoji: '🎪',
    speed: 15.7,
    acceleration: 3.4,
    stamina: 0.75,
    cornering: 0.7,
    weight: 480,
    luck: 0.6,
    specialAbility: 'CIRCUS',
    abilityName: '서커스 퍼포먼스',
    abilityDesc: '깃털 장식과 반짝이 담요를 두른 서커스 말. 달리다가 갑자기 뒷발로 서서 서커스를 시작하는데, 이상하게도 그때 더 빨라진다.',
    description: '관객 박수가 들리면 참지 못한다.',
    bodyColor: 0xf3ede2,
    clothColor: 0xc41e3a,
    silksColor: 0xffd700,
    noseOffset: 2.4,
    strideLength: 6.2,
  },
  {
    id: 'trojan',
    number: 10,
    name: '트로이 목마',
    nameEn: 'TROJAN HORSE',
    nameJa: 'トロイの木馬',
    emoji: '🏛️',
    speed: 15.9,
    acceleration: 2.4,
    stamina: 1.0,
    cornering: 0.5,
    weight: 2600,
    luck: 0.5,
    specialAbility: 'TROJAN',
    abilityName: '병사 출동',
    abilityDesc: '발에 바퀴가 달린 나무 목마. 스태미나가 무한하지만 가속이 느리다. 갑자기 배 쪽 문이 열리고 안에 숨어 있던 병사들이 뛰어나와 뒤에서 밀면 폭발적으로 빨라진다.',
    description: '안에 몇 명이 들어있는지는 아무도 모른다.',
    bodyColor: 0x9a6b3c,
    clothColor: 0x6b2d8f,
    silksColor: 0xc9b037,
    noseOffset: 2.6,
    strideLength: 9.0,
  },
];
